name: pzdart
description: PZ & Naumen SMP integration.
version: 0.0.9
#homepage: https:/naumen.ru
#author: mdemyanov <mdemyanov@naumen.ru>
# java -classpath licensing.jar ru.naumen.licensing.JavaScriptSigner -keystore=nsd40jskey -passwd=vtufgfhjkm -file=main.dart

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  intl: '^0.15.2'
  naumen_smp_rest: '^1.0.1'

dev_dependencies:
  build_web_compilers: '>=0.3.6 <0.5.0'
  build_runner: '>=0.8.10 <0.11.0'

